---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "${path_to_sonarr_config}:/config"
      - "${path_to_tvshows}:/tv" #optional
      - "${path_to_downloads}:/downloads" #optional
    ports:
      - 8989:8989
    restart: unless-stopped