---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "${path_to_radarr_config}:/config"
      - "${path_to_movies}:/movies" #optional
      - "${path_to_downloads}:/downloads" #optional
    ports:
      - 7878:7878
    restart: unless-stopped