services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginx-proxy-manager
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - "{path_to_npm_data}:/data"
      - "{path_to_npm_certs}:/etc/letsencrypt"