---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Homepage
headerStyle: clean
background:
  image: https://wallpapercave.com/wp/wp4565843.jpg
  blur: md
  saturate: 50
  brightness: 50
  opacity: 70
theme: dark
color: slate
useEqualHeights: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
hideVersion: false
layout:
  Infrastructure:
    header: true
    style: row
    columns: 6
  Cloud Apps:
    header: true
    style: row
    columns: 3
  Media:
    header: true
    style: row
    columns: 3
  Access and Services:
    header: true
    style: row
    columns: 4