services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - "${path_to_postgres_config}:/var/lib/postgresql/data"
    environment:
      - PUID=1000
      - PGID=1000
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=default
    