services:
  postgres:
    image: postgres:14-alpine
    container_name:postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=default