---
- name: Deploy gateway apps using Docker Compose
  hosts: all
  become: yes

  tasks:
    
    - name: Ensure Git is installed
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"
      
    - name: Clone the self-hosted repository using https
      git:
        repo: 'https://github.com/{{git_username}}/self-hosted.git'
        dest: /home/{{ ansible_user }}/git/self-hosted
        update: yes
      become_user: "{{ ansible_user }}"

    - name: Set up and deploy Postgres with Docker Compose
      block:
        - name: Create directories for Postgres
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: '0755'
            recurse: yes            
          loop:
            - "{{ path_to_postgres_config }}"
          when: path_to_postgres_config is defined

        - name: Run Docker Compose to deploy Postgres
          shell: docker compose up -d
          args:
            chdir: /home/{{ ansible_user }}/git/self-hosted/apps/postgres
          environment:
            path_to_postgres_config: "{{ lookup('env', 'path_to_postgres_config') }}"
            postgres_password: "{{ lookup('env', 'postgres_password') }}"
          become_user: "{{ ansible_user }}"
          register: docker_compose_output

        - name: Show docker compose output for Postgres
          debug:
            var: docker_compose_output.stdout         

    - name: Set up and deploy Redis with Docker Compose
      block:
        - name: Create directories for Redis
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: '0755'
            recurse: yes            
          loop:
            - "{{ path_to_redis_config }}"
          when: path_to_redis_config is defined

        - name: Run Docker Compose to deploy Redis
          shell: docker compose up -d
          args:
            chdir: /home/{{ ansible_user }}/git/self-hosted/apps/redis
          environment:
            path_to_redis_config: "{{ lookup('env', 'path_to_redis_config') }}"
            redis_password: "{{ lookup('env', 'redis_password') }}"
          become_user: "{{ ansible_user }}"
          register: docker_compose_output

        - name: Show docker compose output for Postgres
          debug:
            var: docker_compose_output.stdout